### ISSUE TITLE
Authentication not successful

### ISSUE THREAD

**Issue by leebaird** [SharpC2/SharpC2#15]
When trying to authenticate to the teamserver, I enter my password and get the Authenticating pop up window.
After about 5 seconds it closes. I don't connect to the teamserver and there is no error.

**Comment by RedTeamWing** [comment]
Me Too

**Comment by jasc22** [comment]
I'm experiencing a similar issue as well.

**Comment by rasta-mouse** [comment]
I've pushed 4a293303a675ad61b4e480d62a1cf3a5635eefad to the dev branch - can you let me know if that solves the issue.

**Comment by rasta-mouse** [comment]
No response, closing.
