### ISSUE TITLE
Looks like that the client.exe maybe is crashing "authenticting" , at time of the authentication?

### ISSUE THREAD

**Issue by bopin2020** [SharpC2/SharpC2#16]
When I ran the client.exe to authenticate for server, but the client.exe  was maybe crashed. Before that, please watch 
[SharpC2_bopin's problem](https://www.youtube.com/watch?v=UglgPEHwlv0)
     Then I started to debug, and found that the source of the problems was that there returned a parameter whose value is null in this file that SharpC2/Client/SharpC2API/ClientAPI.cs  23 lines.
![image](https://user-images.githubusercontent.com/49940777/94273857-8b363c80-ff77-11ea-8446-e065bb8a34a5.png)
![image](https://user-images.githubusercontent.com/49940777/94274117-de0ff400-ff77-11ea-9a30-d87cab1826e0.png)
Before checking, let's understander the authentication process: 
 1. Be sure that TeamServer is running,by default 7443 port is openning
 2. Client  MainWindow.xaml.cs  Initialize the constructor MainWindow 
 3. ConnectViewModel.cs  initialize the ConnectViewModel, and then
 4. ClinetAPI.cs a async Task<> ClientLogin method, POST method request the /api/Client/
    `var apiResponse = await REST.Client.ExecuteAsync(apiRequest);`
    `var result = JsonConvert.DeserializeObject<ClientAuthenticationResult>(apiResponse.Content);`
    when I click the "Connect" button, in ConnectViewModel.cs, the async OnClickLogin method will be executed at the same time, there is a processWindow showing! Before that, everything is well. 
 **My way to analysis**
1. I hit a breakpoint at  `var apiRequest = new RestRequest("/api/Client", Method.POST);` in ClientAPI.cs，I think there is possible because the return apiResponse  returns like `"StatusCode: 0, Content-Type: , Content-Length: 0)"` you can see:
    
![image](https://user-images.githubusercontent.com/49940777/94280136-a147fb00-ff7f-11ea-9628-53b55d93854a.png)
I think the problem is the process that the apiRequest to apiResponse, so I use a python script,and forward network traffic to my burpsuite agent, that's 127.0.0.:8080, here is my python script:
 `import requests
import ssl

url="https://localhost:7443/api/Client"

proxy={"http":"http://127.0.0.1:8080","https":"https://127.0.0.1:8080",}

r=requests.get(url,proxies=proxy,verify=False)

print(r.text)`
 
2. Firstly I use  the httpget method for test: apiRequest a statuscode 401 unauthorized, that's no problem
   
![image](https://user-images.githubusercontent.com/49940777/94281158-df91ea00-ff80-11ea-83bb-de7800c735d6.png)

3. note: TeamServer is running in debug model
   Secondly I use the httppost method and add the Content-Type、Nick、Password  and then TeamServer "request" is also null
 
![image](https://user-images.githubusercontent.com/49940777/94282142-10beea00-ff82-11ea-93ae-b46538814967.png)

 In a word, I think errors are the process that send some data to server, but I don't know why. I guess client.exe sends some errors data to server, so It was crashed.
 Anyone else could help me? I tried my best.

**Comment by rasta-mouse** [comment]
@bopin2020 can you check that the TeamServer is actually bound to `7443`?

```
C:\Users\Rasta>netstat -anop tcp | findstr /i listen | findstr 7443
  TCP    0.0.0.0:7443           0.0.0.0:0              LISTENING       1392
```

**Comment by bopin2020** [comment]
![image](https://user-images.githubusercontent.com/49940777/94285467-41a11e00-ff86-11ea-84b3-cd05065b4bc8.png)
Yes I'm sure. When I kill TeamServer, 7443 port will be disappear

**Comment by bopin2020** [comment]
Now everything is ok! 
![image](https://user-images.githubusercontent.com/49940777/94328048-1fd58480-ffe2-11ea-8546-a6231748cd44.png)
I just emptyed log in TeamServer like this :)
![image](https://user-images.githubusercontent.com/49940777/94328091-5e6b3f00-ffe2-11ea-9b29-da58094f5e4b.png)
The inspiration was from appsettings.json, under the "Urls: "https://0.0.0.0:7443" ", so I found two keys about SharpC2_Log.txt and SharpC2_Log.json. 
Then, I cleaned up them, wanna try again and recover the error, surprisingly, I got loginSuccess and there was no errors. That's prefect, I appraciate that thank you very mush!

**Comment by B1eed** [comment]
It is easy to fix this problem Need to modify the https in the client to http  and the TS port open in 5000

**Comment by bopin2020** [comment]
> It is easy to fix this problem Need to modify the https in the client to http and the TS port open in 5000

BTW, there is a new question which I don't know whether you got
![image](https://user-images.githubusercontent.com/49940777/94354098-4bbc3d00-00aa-11eb-99d7-ecb7b34e117d.png)

**Comment by B1eed** [comment]
I have not used this project anymore (but the author really wrote it very well, I hope the author can improve it and I will use this project again), and there is a small problem that the agent will not reload the module after the TS is closed (hope the author can see)

**Comment by rasta-mouse** [comment]
@B1eed it's still loaded in the agent, it's just that the TS no longer knows about it because it doesn't store data across runs.  There's a new command in the experimental branch that allows an agent to resend all the module data it has loaded.

https://github.com/SharpC2/SharpC2/blob/experimental/SharpC2/TeamServer/Agents/AgentCore/Modules/CoreModule.cs#L43-L48

**Comment by B1eed** [comment]
@rasta-mouse  Thanks for the answer. The project is great!(like the Csharp version of cobaltstrike) ：)
