### ISSUE TITLE
[BUG] NullReferenceException in HandlerScreen.cs

### ISSUE THREAD

**Issue by trickster0** [SharpC2/SharpC2#24]
**Describe the bug**
After going to Handlers in the menu, i typed help then backspace to delete it and i write help again and it crashes as shown in the screenshot, maybe it is the autocomplete popup issue...?

**Screenshots**
![image](https://user-images.githubusercontent.com/20028117/147387855-4fd7e30b-2be5-49bc-a37f-ed00994a85f1.png)

**Environment (please complete the following information):**
Latest kali
.NET6.0

**Comment by trickster0** [comment]
so it happens when i type
help and_whatever_letter_in_the_keyboard

**Comment by rasta-mouse** [comment]
Thanks for the report @trickster0

**Comment by trickster0** [comment]
No problem, sorry to report on xmas :D I had another issue where i could not link with the smb but I am unsure why.
I need to check it again to be sure.
Merry xmas!
