### ISSUE TITLE
[BUG] Client Crashes after starting handler with the same name

### ISSUE THREAD

**Issue by trickster0** [SharpC2/SharpC2#26]
**Describe the bug**
Client Crashes after starting handler with the same name

**To Reproduce**
Create Handler, start it and then try to create one more and start it

**Expected behavior**
Should just say handler already exists or something instead of crashing the client

**Screenshots**
![image](https://user-images.githubusercontent.com/20028117/147952027-13442564-dd95-43ee-a117-6808a34c4a7e.png)

**Comment by rasta-mouse** [comment]
![image](https://user-images.githubusercontent.com/7346521/147954611-57860524-63bf-47cd-9580-3ecb4bc1a412.png)
