### ISSUE TITLE
[BUG] dotnet build 

### ISSUE THREAD

**Issue by piedacoulisse2** [SharpC2/SharpC2#30]
**Describe the bug**
A bug in the installation of SharpC2 after the command : dotnet build
The follow link is not reachable : 
https://nuget.code-offensive.net/v3/index.json

**To Reproduce**
1. Go to repository
2. Run : dotnet build
3. See error
![image](https://user-images.githubusercontent.com/74360897/157009758-22fcb36d-0aa3-433a-a323-d4c11b470914.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - .NET Version 6.0.101

**Comment by rasta-mouse** [comment]
Thanks, nuget server was offline.
