### ISSUE TITLE
[BUG] DonutCore Dependency Removed from nuget

### ISSUE THREAD

**Issue by mohinparamasivam** [SharpC2/SharpC2#31]
**Describe the bug**

DonutCore is no longer available for installation

**SharpC2 Version :** https://github.com/SharpC2/SharpC2/commit/e6d7303bcb11988fb4aa24a60c30bee641e49111

**Environment (please complete the following information):**
 - OS: Windows 8
 - VS Version : Visual Studio 2019

**Screenshots**

![DonutCore_Error](https://user-images.githubusercontent.com/28557040/191478874-c75a0f05-2d0d-4984-b9ac-009371a1bdd0.png)
<br>
![DonutCore_removed](https://user-images.githubusercontent.com/28557040/191478896-867e2ff3-ccb9-4d3d-9772-210b27934f6c.png)

**Comment by rasta-mouse** [comment]
I don't use the package from nuget.org.  I use http://nuget.code-offensive.net/packages/donutcore/1.0.0.
